; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = LilyGoLoraESP32, HeltecLoraV2ESP32
description = io-homecontrol for the ESP32
data_dir = ./extras
extra_configs =
	factory_settings.ini
	features.ini

[common]
framework = arduino
board_build.filesystem = littlefs
lib_deps_builtin = 
lib_deps_external = 
build_flags = 
	-DDEBUG
	-DCORE_DEBUG_LEVEL=5
	-DCONFIG_ESP_WIFI_TASK_PINNED_TO_CORE_1=y
	-DCONFIG_ESP_TIMER_PROFILING=y
	-DCONFIG_ESP_TIMER_SUPPORTS_ISR_DISPATCH_METHOD=y
	-DCONFIG_COMPILER_OPTIMIZATION_PERF=y
	-Wno-attributes
	-I include
	-D APP_NAME=\"iohomecontrol\" ; Must only contain characters from [a-zA-Z0-9-_] as this is converted into a filename
    -D APP_VERSION=\"0.6.0\" ; semver compatible version string
extra_scripts = 

[env]
framework = ${common.framework}
platform = espressif32
platform_packages = platformio/framework-arduinoespressif32
board_build.filesystem = ${common.board_build.filesystem}
build_flags=
	${factory_settings.build_flags}
	${features.build_flags}
	-D NO_GLOBAL_ARDUINOOTA
; Uncomment PROGMEM_WWW to enable the storage of the WWW data in PROGMEM
	-D PROGMEM_WWW
; Uncomment to configure Cross-Origin Resource Sharing
;-D ENABLE_CORS
;-D CORS_ORIGIN=\"*\"
extra_scripts =
	pre:scripts/install_deps.py
    pre:scripts/build_interface.py
    pre:scripts/generate_cert_bundle.py
    scripts/merge_bin.py
    scripts/rename_fw.py
    scripts/save_elf.py
check_tool = 
	cppcheck
	clangtidy
check_skip_packages = yes
lib_ldf_mode = deep
lib_deps = 
	${common.lib_deps_builtin}
	bblanchon/ArduinoJson
	ESP32Async/AsyncTCP
	ESP32Async/ESPAsyncWebServer
	https://github.com/HeMan/async-mqtt-client.git
	adafruit/Adafruit SSD1306 @ ^2.5.15
	tzapu/WiFiManager @ ^2.0.17
	bertmelis/espMqttClient@^1.7.0,<2.0.0
lib_ignore = AsyncTCP-esphome
upload_protocol = esptool
upload_speed = 460800
monitor_speed = 115200
monitor_echo = yes
monitor_filters = 
	esp32_exception_decoder
	send_on_enter
	time
	colorize

; ensure transitive dependencies are included for correct platforms only
lib_compat_mode = strict

; Uncomment to include the a Root CA SSL Certificate Bundle for all SSL needs
; Needs -D FT_DOWNLOAD_FIRMWARE=1 and -D FT_NTP=1
board_build.embed_files = src/certs/x509_crt_bundle.bin
; Source for SSL Cert Store can bei either downloaded from Mozilla with 'mozilla' ('https://curl.se/ca/cacert.pem')
; or from a curated Adafruit repository with 'adafruit' (https://raw.githubusercontent.com/adafruit/certificates/main/data/roots-filtered.pem)
; or complied from a 'folder' full of *.pem / *.dem files stored in the ./ssl_certs folder
;board_ssl_cert_source = mozilla
board_ssl_cert_source = adafruit

[env:debug]
build_type = debug
debug_build_flags = -O0 -ggdb3 -g3

[extra]
build_flags = 
	-std=gnu++2a
	-O3

[env:build_webUI]
platform = native
targets = build
extra_scripts = pre:scripts/build_interface.py
; Exclude all source files so the C code doesn't build
build_src_filter = -<*>

[env:HeltecLoraV2ESP32]
board = heltec_wifi_lora_32_V2
build_unflags = 
	-std=gnu++11
	-Os
build_flags = 
	-DHELTEC
	${common.build_flags}
	${extra.build_flags}

[env:LilyGoLoraESP32]
board = ttgo-lora32-v21
board_build.partitions = no_ota.csv
build_unflags = 
	-std=gnu++11
	-Os
build_flags = 
	-DLILYGO
	${common.build_flags}
	${extra.build_flags}
